services:
  backend-ventas:
    image: ${VENTAS_BACKEND_IMAGE}
    container_name: innovatech-ventas-backend
    restart: unless-stopped
    environment:
      DB_ENDPOINT: ${DATA_PRIVATE_IP}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:8080"

  backend-despachos:
    image: ${DESPACHOS_BACKEND_IMAGE}
    container_name: innovatech-despachos-backend
    restart: unless-stopped
    environment:
      DB_ENDPOINT: ${DATA_PRIVATE_IP}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:8081"
