services:
  mysql:
    image: mysql:8.0
    container_name: innovatech-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - innovatech_mysql_data:/var/lib/mysql
volumes:
  innovatech_mysql_data:
    name: innovatech_mysql_data
